export interface StoreProduct {
  id: string;
  title_tr: string;
  title_en: string;
  title_ar: string;
  brand: string;
  category: 'telefon' | 'laptop' | 'robot' | 'watch' | 'kulaklik' | 'aksesuar' | 'yedek_parca' | string;
  part_type?: 'ekran' | 'batarya' | 'sarj_soketi' | 'arka_kapak' | 'kamera' | 'hoparlor' | 'mikrofon' | 'yan_tuslar' | 'flex' | 'anakart' | 'diger' | string;
  item_type: 'cihaz' | 'yedek_parca' | 'aksesuar' | string;
  series?: string;
  model: string;
  specs_tr: string;
  specs_en: string;
  specs_ar: string;
  price: number;
  max_price?: number;
  old_price?: number;
  quality?: 'Orijinal' | 'OEM' | 'Muadil' | 'Çıkma' | string;
  color?: string;
  in_stock: boolean;
  is_popular?: boolean;
  is_featured?: boolean;
  badge?: string;
  show_badge?: boolean;
  badge_text_tr?: string;
  badge_text_en?: string;
  badge_text_ar?: string;
  image: string;
  images?: string[];
  description_tr?: string;
  description_en?: string;
  description_ar?: string;
}

export const STORE_CATEGORIES = [
  {
    id: 'telefon',
    title_tr: 'Telefon',
    title_en: 'Phone',
    title_ar: 'الهواتف',
    desc_tr: 'iPhone, Samsung, Xiaomi ve Daha Fazlası',
    desc_en: 'iPhone, Samsung, Xiaomi and More',
    desc_ar: 'آيفون، سامسونج، شاومي والمزيد',
    image: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?q=80&w=800&auto=format&fit=crop',
    href: '/urunler?category=telefon',
    banner_image: '/images/phones-banner.jpg',
    banner_title_ar: 'متجر الهواتف الذكية وقطع الغيار الأصلية',
    banner_title_tr: 'Akıllı Telefonlar & Orijinal Parçalar',
    banner_title_en: 'Smartphones & Genuine Spare Parts',
    banner_desc_ar: 'شاشات وكالة، بطاريات عالية الأداء، أجهزة معتمدة وإكسسوارات بضمان المنتج الرسمي وشحن وتوصيل فوري.',
    banner_desc_tr: 'Orijinal ekranlar, yüksek kapasiteli bataryalar ve cihazlar. Resmi ürün garantisi ve hızlı teslimat.',
    banner_desc_en: 'Original screens, high capacity batteries, and devices with official warranty and fast shipping.',
    banner_cta_ar: 'استعراض منتجات الهواتف',
    banner_cta_tr: 'Telefon Ürünlerini İncele',
    banner_cta_en: 'Explore Phone Products'
  },
  {
    id: 'laptop',
    title_tr: 'Laptop',
    title_en: 'Laptop',
    title_ar: 'اللابتوب',
    desc_tr: 'Tüm Markalar ve Yedek Parçalar',
    desc_en: 'All Brands and Spare Parts',
    desc_ar: 'كافة الماركات وقطع الغيار',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=800&auto=format&fit=crop',
    href: '/urunler?category=laptop',
    banner_image: '/images/laptops-banner.jpg',
    banner_title_ar: 'أجهزة اللابتوب والماك بوك ومستلزماتها',
    banner_title_tr: 'Laptop, MacBook & Yedek Parçaları',
    banner_title_en: 'Laptops, MacBooks & Spare Parts',
    banner_desc_ar: 'شاشات لابتوب، بطاريات موثوقة، كيبوردات وشواحن لكافة الماركات العالمية متوافقة 100% مع ضمان المنتج.',
    banner_desc_tr: 'Tüm markalar için ekran, batarya, klavye ve şarj adaptörleri. %100 uyumluluk garantisi.',
    banner_desc_en: 'Screens, batteries, keyboards, and adapters for all laptop brands with guaranteed compatibility.',
    banner_cta_ar: 'استعراض منتجات اللابتوب',
    banner_cta_tr: 'Laptopları İncele',
    banner_cta_en: 'Explore Laptop Products'
  },
  {
    id: 'robot',
    title_tr: 'Robot Süpürge',
    title_en: 'Robot Vacuum',
    title_ar: 'المكانس الروبوتية',
    desc_tr: 'Cihazlar ve Yedek Parçalar',
    desc_en: 'Devices and Spare Parts',
    desc_ar: 'الأجهزة وقطع الغيار',
    image: '/robot.png',
    href: '/urunler?category=robot',
    banner_image: 'https://images.unsplash.com/photo-1518133835878-5a93cc3f89e5?q=80&w=1600&auto=format&fit=crop',
    banner_title_ar: 'المكانس الروبوتية ومستلزماتها وقطع غيارها',
    banner_title_tr: 'Robot Süpürgeler & Sarf Malzemeleri',
    banner_title_en: 'Robot Vacuums & Accessories',
    banner_desc_ar: 'فلاتر أصلية، فرش، بطاريات ومستلزمات متوافقة مع أشهر ماركات المكانس الذكية مع شحن فوري.',
    banner_desc_tr: 'Orijinal filtreler, fırçalar, bataryalar ve aksesuarlar. Tüm popüler robot modelleriyle uyumlu.',
    banner_desc_en: 'Original filters, brushes, batteries, and accessories compatible with top robot vacuum brands.',
    banner_cta_ar: 'استعراض منتجات المكانس',
    banner_cta_tr: 'Süpürgeleri İncele',
    banner_cta_en: 'Explore Vacuum Products'
  },
  {
    id: 'watch',
    title_tr: 'Akıllı Saat',
    title_en: 'Smart Watch',
    title_ar: 'الساعات الذكية',
    desc_tr: 'Orijinal ve Uyumlu Ürünler',
    desc_en: 'Original and Compatible Products',
    desc_ar: 'منتجات أصلية ومتوافقة',
    image: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?q=80&w=800&auto=format&fit=crop',
    href: '/urunler?category=watch',
    banner_image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?q=80&w=1600&auto=format&fit=crop',
    banner_title_ar: 'الساعات الذكية وشاشاتها وإكسسواراتها الأصلية',
    banner_title_tr: 'Akıllı Saatler & Ekran/Kordon Çeşitleri',
    banner_title_en: 'Smart Watches & Accessories',
    banner_desc_ar: 'شاشات وكالة، بطاريات وسوارات متميزة لساعات أبل وجالكسي وهواوي بضمان جودة عالي.',
    banner_desc_tr: 'Apple Watch ve Galaxy Watch için orijinal ekranlar, bataryalar ve şık kordon modelleri.',
    banner_desc_en: 'Original screens, batteries, and straps for Apple Watch, Galaxy Watch, and more.',
    banner_cta_ar: 'استعراض الساعات الذكية',
    banner_cta_tr: 'Saatleri İncele',
    banner_cta_en: 'Explore Watch Products'
  },
  {
    id: 'kulaklik',
    title_tr: 'Kulaklık',
    title_en: 'Earbuds & Headphones',
    title_ar: 'السماعات',
    desc_tr: 'AirPods, Samsung, Xiaomi ve Daha Fazlası',
    desc_en: 'AirPods, Samsung, Xiaomi and More',
    desc_ar: 'ايربودز، سامسونج، شاومي وغيرها',
    image: '/airpods.png',
    href: '/urunler?category=kulaklik',
    banner_image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1600&auto=format&fit=crop',
    banner_title_ar: 'سماعات البلوتوث اللاسلكية والرأسية المعتمدة',
    banner_title_tr: 'Kulaklıklar & Kablosuz Ses Sistemleri',
    banner_title_en: 'Headphones & Wireless Earbuds',
    banner_desc_ar: 'سماعات AirPods وموديلات سامسونج وشاومي بنقاء صوت ممتاز وعزل ضوضاء وضمان موثوق.',
    banner_desc_tr: 'AirPods ve kablosuz kulaklıklar, üstün ses kalitesi, aktif gürültü engelleme ve resmi garanti.',
    banner_desc_en: 'AirPods and wireless earbuds with superior sound quality, active noise cancellation, and warranty.',
    banner_cta_ar: 'استعراض السماعات',
    banner_cta_tr: 'Kulaklıkları İncele',
    banner_cta_en: 'Explore Headphones'
  },
  {
    id: 'aksesuar',
    title_tr: 'Aksesuar',
    title_en: 'Accessories',
    title_ar: 'الإكسسوارات',
    desc_tr: 'Şarj Aletleri, Kablolar, Kılıflar ve Daha Fazlası',
    desc_en: 'Chargers, Cables, Cases and More',
    desc_ar: 'شواحن، كابلات، كفرات والمزيد',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?q=80&w=800&auto=format&fit=crop',
    href: '/urunler?category=aksesuar',
    banner_image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?q=80&w=1600&auto=format&fit=crop',
    banner_title_ar: 'الإكسسوارات وملحقات الشحن والحماية',
    banner_title_tr: 'Aksesuarlar & Şarj ve Koruma Ürünleri',
    banner_title_en: 'Accessories & Protection',
    banner_desc_ar: 'شواحن سريعة معتمدة، كابلات فائقة المتانة، وحافظات كفرات لحماية أجهزتك بأناقة.',
    banner_desc_tr: 'Hızlı şarj adaptörleri, dayanıklı örgü kablolar ve darbelere dayanıklı şık kılıflar.',
    banner_desc_en: 'Fast chargers, durable braided cables, and shockproof protective cases.',
    banner_cta_ar: 'استعراض الإكسسوارات',
    banner_cta_tr: 'Aksesuarları İncele',
    banner_cta_en: 'Explore Accessories'
  },
  {
    id: 'yedek_parca',
    title_tr: 'Yedek Parçalar',
    title_en: 'Spare Parts',
    title_ar: 'قطع الغيار',
    desc_tr: 'Ekran, Batarya, Kamera ve Diğer Parçalar',
    desc_en: 'Screen, Battery, Camera and More',
    desc_ar: 'شاشات، بطاريات، كاميرات والمزيد',
    image: '/images/spare-parts-screen.jpg',
    href: '/urunler?category=yedek_parca',
    banner_image: '/images/parts-banner.jpg',
    banner_title_ar: 'قطع الغيار الأصلية المعتمدة لجميع الأجهزة',
    banner_title_tr: 'Orijinal & A+ Kalite Yedek Parçalar',
    banner_title_en: 'Genuine & High Quality Spare Parts',
    banner_desc_ar: 'شاشات سيرفس وكالة، بطاريات عالية الأداء، منافذ شحن وكاميرات خاضعة للفحص مع ضمان حقيقي.',
    banner_desc_tr: 'Ekran, batarya, kamera ve entegreler. Test edilmiş güvenilir parçalar ve ürün garantisi.',
    banner_desc_en: 'Service pack screens, batteries, cameras, and tested chips with genuine product warranty.',
    banner_cta_ar: 'استعراض قطع الغيار',
    banner_cta_tr: 'Parçaları İncele',
    banner_cta_en: 'Explore Spare Parts'
  }
];

export const STORE_BRANDS = [
  { id: 'Apple', name: 'iPhone / Apple' },
  { id: 'Samsung', name: 'Samsung' },
  { id: 'Xiaomi', name: 'Xiaomi' },
  { id: 'Oppo', name: 'Oppo' },
  { id: 'Huawei', name: 'Huawei' },
  { id: 'OnePlus', name: 'OnePlus' },
  { id: 'Realme', name: 'Realme' },
  { id: 'ASUS', name: 'ASUS' },
  { id: 'Lenovo', name: 'Lenovo' },
  { id: 'HP', name: 'HP' },
  { id: 'Dell', name: 'Dell' },
  { id: 'Roborock', name: 'Roborock' },
];

export const SPARE_PARTS_MENU = [
  { id: 'ekran', label_tr: 'Ekran', label_en: 'Screen', label_ar: 'شاشات' },
  { id: 'batarya', label_tr: 'Batarya', label_en: 'Battery', label_ar: 'بطاريات' },
  { id: 'sarj_soketi', label_tr: 'Şarj Soketi', label_en: 'Charging Port', label_ar: 'منافذ الشحن' },
  { id: 'arka_kapak', label_tr: 'Arka Kapak', label_en: 'Back Cover', label_ar: 'الغطاء الخلفي' },
  { id: 'kamera', label_tr: 'Kamera', label_en: 'Camera', label_ar: 'كاميرات' },
  { id: 'hoparlor', label_tr: 'Hoparlör', label_en: 'Speaker', label_ar: 'مكبرات الصوت' },
  { id: 'mikrofon', label_tr: 'Mikrofon', label_en: 'Microphone', label_ar: 'الميكروفونات' },
  { id: 'yan_tuslar', label_tr: 'Yan Tuşlar', label_en: 'Side Buttons', label_ar: 'الأزرار الجانبية' },
  { id: 'flex', label_tr: 'Flex Kablolar', label_en: 'Flex Cables', label_ar: 'كابلات الفليكس' },
  { id: 'anakart', label_tr: 'Anakart Parçaları', label_en: 'Motherboard Parts', label_ar: 'قطع المذربورد' },
  { id: 'diger', label_tr: 'Diğer Parçalar', label_en: 'Other Parts', label_ar: 'قطع أخرى' }
];

export const IPHONE_SERIES = [
  'Tüm Modeller',
  'iPhone 15 Serisi',
  'iPhone 14 Serisi',
  'iPhone 13 Serisi',
  'iPhone 12 Serisi',
  'iPhone 11 Serisi',
  'iPhone X Serisi',
  'iPhone 8 Serisi',
  'iPhone 7 Serisi',
  'Diğer Modeller'
];

export const INITIAL_STORE_PRODUCTS: StoreProduct[] = [
  // --- Exact Match From Screenshot 3: Phones & Devices ---
  {
    id: 'p-dev-1',
    title_tr: 'iPhone 15 Pro Max',
    title_en: 'iPhone 15 Pro Max',
    title_ar: 'آيفون 15 برو ماكس',
    brand: 'Apple',
    category: 'telefon',
    item_type: 'cihaz',
    series: 'iPhone 15 Serisi',
    model: 'iPhone 15 Pro Max',
    specs_tr: 'Sıfır - 256 GB',
    specs_en: 'Brand New - 256 GB',
    specs_ar: 'جديد كلياً - 256 جيجابايت',
    price: 52999,
    badge: 'Cihaz',
    in_stock: true,
    is_popular: true,
    image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'p-dev-2',
    title_tr: 'Samsung Galaxy S24 Ultra',
    title_en: 'Samsung Galaxy S24 Ultra',
    title_ar: 'سامسونج جالاكسي S24 ألترا',
    brand: 'Samsung',
    category: 'telefon',
    item_type: 'cihaz',
    series: 'Galaxy S24',
    model: 'S24 Ultra',
    specs_tr: 'Sıfır - 256 GB',
    specs_en: 'Brand New - 256 GB',
    specs_ar: 'جديد كلياً - 256 جيجابايت',
    price: 48999,
    badge: 'Cihaz',
    in_stock: true,
    is_popular: true,
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'p-dev-3',
    title_tr: 'Xiaomi 14',
    title_en: 'Xiaomi 14',
    title_ar: 'شاومي 14',
    brand: 'Xiaomi',
    category: 'telefon',
    item_type: 'cihaz',
    series: 'Xiaomi 14 Serisi',
    model: 'Xiaomi 14',
    specs_tr: 'Sıfır - 256 GB',
    specs_en: 'Brand New - 256 GB',
    specs_ar: 'جديد كلياً - 256 جيجابايت',
    price: 32999,
    badge: 'Cihaz',
    in_stock: true,
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?q=80&w=800&auto=format&fit=crop'
  },

  // --- Exact Match From Screenshot 2 & 3: Spare Parts ---
  {
    id: 'p-part-1',
    title_tr: 'iPhone 15 Ekran (Orijinal)',
    title_en: 'iPhone 15 Screen (Original)',
    title_ar: 'شاشة آيفون 15 (أصلية)',
    brand: 'Apple',
    category: 'yedek_parca',
    part_type: 'ekran',
    item_type: 'yedek_parca',
    series: 'iPhone 15 Serisi',
    model: 'iPhone 15',
    specs_tr: 'A+ Kalite • True Tone Destekli',
    specs_en: 'A+ Grade • True Tone Supported',
    specs_ar: 'نخب أول A+ • تدعم ترو تون',
    price: 5250,
    quality: 'Orijinal',
    badge: 'Orijinal',
    in_stock: true,
    is_popular: true,
    is_featured: true,
    image: '/images/spare-parts-screen.jpg'
  },
  {
    id: 'p-part-2',
    title_tr: 'iPhone 15 Ekran (OEM)',
    title_en: 'iPhone 15 Screen (OEM)',
    title_ar: 'شاشة آيفون 15 (OEM)',
    brand: 'Apple',
    category: 'yedek_parca',
    part_type: 'ekran',
    item_type: 'yedek_parca',
    series: 'iPhone 15 Serisi',
    model: 'iPhone 15',
    specs_tr: 'Yüksek Kalite • True Tone Destekli',
    specs_en: 'High Quality • True Tone Supported',
    specs_ar: 'جودة عالية • تدعم ترو تون',
    price: 3750,
    quality: 'OEM',
    badge: 'OEM',
    in_stock: true,
    is_featured: true,
    image: '/images/spare-parts-screen.jpg'
  },
  {
    id: 'p-part-3',
    title_tr: 'iPhone 15 Ekran (Muadil)',
    title_en: 'iPhone 15 Screen (Compatible)',
    title_ar: 'شاشة آيفون 15 (معادلة)',
    brand: 'Apple',
    category: 'yedek_parca',
    part_type: 'ekran',
    item_type: 'yedek_parca',
    series: 'iPhone 15 Serisi',
    model: 'iPhone 15',
    specs_tr: 'Ekonomik Seçenek',
    specs_en: 'Economy Choice',
    specs_ar: 'خيار اقتصادي ممتاز',
    price: 2450,
    quality: 'Muadil',
    badge: 'Muadil',
    in_stock: true,
    image: '/images/spare-parts-screen.jpg'
  },
  {
    id: 'p-part-4',
    title_tr: 'iPhone 15 Plus Ekran (Orijinal)',
    title_en: 'iPhone 15 Plus Screen (Original)',
    title_ar: 'شاشة آيفون 15 بلس (أصلية)',
    brand: 'Apple',
    category: 'yedek_parca',
    part_type: 'ekran',
    item_type: 'yedek_parca',
    series: 'iPhone 15 Serisi',
    model: 'iPhone 15 Plus',
    specs_tr: 'A+ Kalite • True Tone Destekli',
    specs_en: 'A+ Grade • True Tone Supported',
    specs_ar: 'نخب أول A+ • تدعم ترو تون',
    price: 6250,
    quality: 'Orijinal',
    badge: 'Orijinal',
    in_stock: true,
    image: '/images/spare-parts-screen.jpg'
  },
  {
    id: 'p-part-5',
    title_tr: 'Samsung S23 Batarya (Orijinal)',
    title_en: 'Samsung S23 Battery (Original)',
    title_ar: 'بطارية سامسونج S23 (أصلية)',
    brand: 'Samsung',
    category: 'yedek_parca',
    part_type: 'batarya',
    item_type: 'yedek_parca',
    series: 'Galaxy S23',
    model: 'Galaxy S23',
    specs_tr: '3900 mAh • Orijinal Samsung',
    specs_en: '3900 mAh • Original Samsung',
    specs_ar: '3900 مللي أمبير • سامسونج أصلية',
    price: 1450,
    quality: 'Orijinal',
    badge: 'Yedek Parça',
    in_stock: true,
    image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'p-part-6',
    title_tr: 'iPhone 14 Kamera (Orijinal)',
    title_en: 'iPhone 14 Camera (Original)',
    title_ar: 'كاميرا آيفون 14 (أصلية)',
    brand: 'Apple',
    category: 'yedek_parca',
    part_type: 'kamera',
    item_type: 'yedek_parca',
    series: 'iPhone 14 Serisi',
    model: 'iPhone 14',
    specs_tr: 'Orijinal Çıkma Lens ve Sensör',
    specs_en: 'Original Pull Lens and Sensor',
    specs_ar: 'عدسة ومستشعر أصلي وكالة',
    price: 3250,
    quality: 'Orijinal',
    badge: 'Yedek Parça',
    in_stock: true,
    image: 'https://images.unsplash.com/photo-1588508065123-287b28e013da?q=80&w=800&auto=format&fit=crop'
  },

  // --- Exact Match From Screenshot 3: Accessories ---
  {
    id: 'p-acc-1',
    title_tr: 'iPhone 15 Kılıf (Silikon)',
    title_en: 'iPhone 15 Case (Silicone)',
    title_ar: 'كفر آيفون 15 (سيليكون فاخر)',
    brand: 'Apple',
    category: 'aksesuar',
    item_type: 'aksesuar',
    series: 'iPhone 15 Serisi',
    model: 'iPhone 15',
    specs_tr: 'Kadife İç Yüzey • MagSafe Uyumlu',
    specs_en: 'Velvet Inner • MagSafe Compatible',
    specs_ar: 'بطانة مخملية • يدعم ماج سيف',
    price: 450,
    badge: 'Aksesuar',
    in_stock: true,
    image: 'https://images.unsplash.com/photo-1601593346740-925612772716?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'p-acc-2',
    title_tr: 'Samsung Hızlı Şarj Aleti',
    title_en: 'Samsung Fast Charger',
    title_ar: 'شاحن سامسونج فائق السرعة',
    brand: 'Samsung',
    category: 'aksesuar',
    item_type: 'aksesuar',
    model: '45W PD Type-C',
    specs_tr: '45W Type-C Hızlı Şarj Başlığı',
    specs_en: '45W Type-C Super Fast Adapter',
    specs_ar: 'رأس شحن سريع 45 واط Type-C',
    price: 690,
    badge: 'Aksesuar',
    in_stock: true,
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'p-acc-3',
    title_tr: 'Xiaomi Kulaklık (Type-C)',
    title_en: 'Xiaomi Earphones (Type-C)',
    title_ar: 'سماعات شاومي سلكية (Type-C)',
    brand: 'Xiaomi',
    category: 'aksesuar',
    item_type: 'aksesuar',
    model: 'Type-C Earbuds',
    specs_tr: 'HD Mikrofonlu Kablolu Kulaklık',
    specs_en: 'Wired Earbuds with HD Mic',
    specs_ar: 'سماعات سلكية مع مايك عالي الدقة',
    price: 390,
    badge: 'Aksesuar',
    in_stock: true,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'p-acc-4',
    title_tr: 'iPhone 15 Ekran Koruyucu',
    title_en: 'iPhone 15 Screen Protector',
    title_ar: 'حامي شاشة آيفون 15',
    brand: 'Apple',
    category: 'aksesuar',
    item_type: 'aksesuar',
    series: 'iPhone 15 Serisi',
    model: 'iPhone 15',
    specs_tr: '9H Sertlik • Kenardan Kenara Tam Koruma',
    specs_en: '9H Hardness • Edge-to-Edge Protection',
    specs_ar: 'صلابة 9H • حماية كاملة من الحافة للحافة',
    price: 250,
    badge: 'Aksesuar',
    in_stock: true,
    image: 'https://images.unsplash.com/photo-1591337676887-a217a6970a8a?q=80&w=800&auto=format&fit=crop'
  },

  // --- Laptops & Robot Süpürge ---
  {
    id: 'p-lap-1',
    title_tr: 'MacBook Pro 14" M3',
    title_en: 'MacBook Pro 14" M3',
    title_ar: 'ماك بوك برو 14 إنش M3',
    brand: 'Apple',
    category: 'laptop',
    item_type: 'cihaz',
    model: 'MacBook Pro M3',
    specs_tr: '512 GB SSD - 18 GB Unified RAM',
    specs_en: '512 GB SSD - 18 GB Unified RAM',
    specs_ar: '512 جيجابايت SSD - رام 18 جيجابايت',
    price: 74999,
    badge: 'Cihaz',
    in_stock: true,
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'p-rob-1',
    title_tr: 'Roborock S8 Pro Ultra',
    title_en: 'Roborock S8 Pro Ultra',
    title_ar: 'روبوروك S8 برو ألترا',
    brand: 'Roborock',
    category: 'robot',
    item_type: 'cihaz',
    model: 'S8 Pro Ultra',
    specs_tr: 'Otomatik Yıkama ve Kurulama İstasyonu',
    specs_en: 'Auto Wash & Empty Station',
    specs_ar: 'محطة غسيل وتجفيف وتفريغ تلقائي',
    price: 43999,
    badge: 'Cihaz',
    in_stock: true,
    image: '/robot.png'
  },
  {
    id: 'p-wat-1',
    title_tr: 'Apple Watch Ultra 2',
    title_en: 'Apple Watch Ultra 2',
    title_ar: 'أبل واتش ألترا 2',
    brand: 'Apple',
    category: 'watch',
    item_type: 'cihaz',
    model: 'Watch Ultra 2',
    specs_tr: '49mm Titanyum Kasa • GPS + Cellular',
    specs_en: '49mm Titanium Case • GPS + Cellular',
    specs_ar: 'هيكل تيتانيوم 49 مم • GPS وشريحة',
    price: 39999,
    badge: 'Cihaz',
    in_stock: true,
    image: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'p-ear-1',
    title_tr: 'AirPods Pro 2 (USB-C)',
    title_en: 'AirPods Pro 2 (USB-C)',
    title_ar: 'إيربودز برو 2 (USB-C)',
    brand: 'Apple',
    category: 'kulaklik',
    item_type: 'cihaz',
    model: 'AirPods Pro 2',
    specs_tr: 'Aktif Gürültü Engelleme • MagSafe',
    specs_en: 'Active Noise Cancellation • MagSafe',
    specs_ar: 'عزل ضوضاء نشط • شحن ماج سيف',
    price: 9499,
    badge: 'Cihaz',
    in_stock: true,
    image: '/airpods.png'
  }
];
